feat: add definitions and modify discover
ftrackhq/ftrack-connect-pipeline-houdini pull request #4
Opened 2023-02-17 10:41 UTC by lluisCM

Resolves 

- [ ] I have added automatic tests where applicable.
- [ ] The PR contains a description of what has been changed.
- [ ] The description contains manual test instructions.
- [ ] The PR contains updates to the release notes.
- [ ] I have verified that the documentation is still up to date.

## Changes

All definitions are moved to each integration, schemas are in pipeline. Collection and validation of the definitions happen on host.
## Test

2023-02-17 13:59 UTC, henriknorin-ftrack approved these changes

2023-02-17 14:14 UTC, henriknorin-ftrack requested changes
See my comment on review mistake, approach to correct this:

1. Move python3.7libs and python3.9libs out of plugins folder.
2. Remove unused plugins folder
3. Remove unused houdini_bootstrap_plugin_path and not append it to HOUDINI_PATH, e.g. set HOUDINI_PATH to houdini_path_append.

2023-02-17 14:14 UTC, henriknorin-ftrack commented on hook/discover_houdini.py
> +        houdini_bootstrap_path, 'plugins'
I made a mistake reviewing your previous PR, the pythonrc.py:s are not DCC plugins, they are bootstrap scripts so they should go above the "plugins" folder.

2023-02-17 14:14 UTC, henriknorin-ftrack commented on hook/discover_houdini.py
>              [houdini_path_append, houdini_bootstrap_plugin_path]
houdini_bootstrap_plugin_path should not be added here, it is not used.

2023-02-17 14:15 UTC, henriknorin-ftrack commented
Lets also make a neater approach to the bootstrap scripts (pythonrc.py:s), which not contains duplicate code, with next Python interpreter version upgrade in Houdini

2023-02-20 08:39 UTC, lluisCM commented on hook/discover_houdini.py
> +        houdini_bootstrap_path, 'plugins'
Done

2023-02-20 08:39 UTC, lluisCM commented on hook/discover_houdini.py
>              [houdini_path_append, houdini_bootstrap_plugin_path]
Leaving it there for consistency with the other DCCs, so if the user wants to put a plugin should be able to read it from there.

2023-02-20 08:45 UTC, henriknorin-ftrack requested changes

2023-02-20 08:45 UTC, henriknorin-ftrack commented on hook/discover_houdini.py
>              [houdini_path_append, houdini_bootstrap_plugin_path]
It will not work, Houdini requires a "&" between each entry in HOUDINI_PATH, so you will need to check if houdini_bootstrap_plugin_path exists and then prepare it the same way as houdini_path_append is done.

2023-02-20 08:45 UTC, henriknorin-ftrack commented on hook/discover_houdini.py
>              [houdini_path_append, houdini_bootstrap_plugin_path]
Agree on the consistency

2023-02-20 11:16 UTC, henriknorin-ftrack approved these changes
Just that change to if statement logic

2023-02-20 11:16 UTC, henriknorin-ftrack commented on hook/discover_houdini.py
> +        if os.environ.get('HOUDINI_PATH', '').endswith('&')
Would do:  
if len(os.environ.get('HOUDINI_PATH', ''))>0

Right now it will only add the '&' if the existing HOUDINI_PATH ends with the '&'

2023-02-20 11:18 UTC, merged