feat: Backlog/fix houdini exporters
ftrackhq/ftrack-connect-pipeline-houdini pull request #9
Opened 2023-03-14 14:59 UTC by henriknorin-ftrack

Resolves : 

* CLICKUP-865by8m8c

- [ ] I have added automatic tests where applicable.
- [ ] The PR contains a description of what has been changed.
- [ ] The description contains manual test instructions.
- [X] The PR contains update to the release notes.
- [ ] The PR contains update to the documentation.

This PR has been tested on :

- [ ] Windows.
- [X] MacOs.
- [ ] Linux.

## Changes

- Fixed UI bugs in Alembic and FBX exporter
- Added frame range and take options to FBX exporter, enabling export of animations
- Displays collected camera in exporter

## Test

_Note: needs to be tested on corresponding branches on QT and Houdini._

Test FBX and Alembic export, with geometry and camera publishers. Validate UI options and validate the results in other DCC.

2023-03-15 10:19 UTC, lluisCM requested changes
See comments

2023-03-15 10:19 UTC, lluisCM commented on resource/definitions/publisher/camera-houdini-publish.json
> +              "widget": "houdini_camera_publisher_collector"
FYI this is not needed, we don't need to specify the widget, it should automatically be picked up. (But ok for me to leave it, this is just info)

2023-03-15 10:19 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/houdini_abc_publisher_exporter.py
> +            # Clean up after us
Shouldn't we catch an exception in case something fails?

2023-03-15 10:19 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/houdini_fbx_publisher_exporter.py
> +            pass  # Not supported in older versions
Why don't we have the exception?

2023-03-15 10:19 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/houdini_fbx_publisher_exporter.py
>          finally:
Same here, why without Exception?

2023-03-15 10:19 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/widget/houdini_abc_publisher_exporter_options.py
> +            "ABCFormat": ["Default", "HDF5", "Ogawa"],
Shouldn't we add this one in the exporter as well?

2023-03-15 10:26 UTC, lluisCM requested changes

2023-03-15 10:26 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/widget/houdini_abc_publisher_exporter_options.py
> +        self._get_widget('ABCFrameRangeEnd').setText(str(result['frameEnd']))
Why don't we fetch as we do in maya or in any other DCC? so we don't have to modify QT now? I think there are other ways to fix this now so we don't have to test all the DCCs again. And we can evaluate to introduce this later.

2023-03-15 11:12 UTC, henriknorin-ftrack commented on resource/definitions/publisher/camera-houdini-publish.json
> +              "widget": "houdini_camera_publisher_collector"
This is a decision to be made, in some sense it is nice to be explicit and have this statement which points out there is a widget. Otherwise you do not know if there is supposed to be a widget or not, which is confusing during debugging. Lets discuss OOB

2023-03-15 11:14 UTC, henriknorin-ftrack commented on resource/definitions/publisher/camera-houdini-publish.json
> +              "widget": "houdini_camera_publisher_collector"
Decided to keep

2023-03-15 11:18 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/houdini_fbx_publisher_exporter.py
> +            pass  # Not supported in older versions
I removed the try catch, this is supported fully out now and can be brought back if client asks for it.

2023-03-15 11:20 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/widget/houdini_abc_publisher_exporter_options.py
> +            "ABCFormat": ["Default", "HDF5", "Ogawa"],
Well spotted

2023-03-15 11:24 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/widget/houdini_abc_publisher_exporter_options.py
> +        self._get_widget('ABCFrameRangeEnd').setText(str(result['frameEnd']))
We only added a new function (_get_widget), no refactoring done, and tests has been done in other DCCs. 

In Maya we are not using the DynamicWidget to render frame range inputs, a crude solution IMO which adds more duplicate code to maintain. By using the DynamicWidget, and evolving it, we will have faster development cycles across DCCs.

2023-03-15 14:49 UTC, henriknorin-ftrack commented
Disabled the having fetch functions update dynamic widget frame range input.

2023-03-16 07:57 UTC, lluisCM approved these changes
LGTM

2023-03-16 08:24 UTC, merged